// Kategori yang boleh ditampilkan di katalog publik
const ALLOWED_CATEGORIES = new Set([
  "Snack & Sides",
  "Menu Crisbro",
  "Crisbar Korean Chicken",
  "CMP",
  "My Kisah Katsu <3",
  "Crisbarbar Whole Chicken",
  "Cocolove Stories 🫶",
  "Mood Booster Drinks",
  "Topping",
  "Best Seller Bundling",
  "Landing Page Kampus",
  "Little Hero Crisbar",
  "Cita Rasa Nusantara",
  "Paket Ayam Crisbar",
  "Keju Salju Sensasi Baru",
  "#TeamCool",
  "Paket Ayam Crisbee",
  "#TeamHot",
  "Paket Ayam Spicy",
  "Keju Mozzarella Naikin Mood",
  "It's DJ Time!!",
  "Bundling Tea Series",
  "Raos Pisan",
  "Skin Lovers Squad",
  "Teman Gawe",
  "Nasi Kulit",
  "Crisbar Coffe",
  "Survival Kit",
  "Smart Deal",
]);

module.exports = { ALLOWED_CATEGORIES };